language: python # this works for Linux but is an error on macOS or Windows

jobs:
  include:
    - stage: "Tests"
      name: "Test bionic Python 3.6"
      os: linux
      dist: bionic
      python: "3.6"
      env: TOXENV=py36
    - name: "Test bionic Python 3.8"
      os: linux
      dist: bionic
      python: "3.8"
      env: TOXENV=py38
    - name: "Test OSX Python default version"
      os: osx
      language: shell # 'language: python' is an error on Travis CI macOS
      env: TOXENV=py3
    - name: "Test Windows Python 3.8.0"
      os: windows
      language: shell # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - TOXENV=py38
    - stage: before_deploy
        - pip3 install .
        - pip3 install pyinstaller
        - pyinstaller --additional-hooks-dir=pyinstaller_hooks/ travisty/__main__.py  --name travisty --workpath=build/pyinstaller_work --distpath=build
        - ls -lh build/travesty
        - tar cvfz travesty.${TRAVIS_OS_NAME}.tar.gz build/travisty/
    - stage: deploy
      skip_cleanup: true
      on:
        - tags: true
      - name: "Deploy macOS binary to github release"
        provider: releases
        user: $GITHUB_PASSWORD
        password: $GITHUB_PASSWORD
        on:
          - condition: $TRAVIS_OS_NAME = osx
        api_key: "GITHUB OAUTH TOKEN"
        file: travesty.mac.tar.gz
        skip_existing: true



install:
  pip install tox

script: tox -e $TOXENV

#deploy:
#  provider: pypi
#  user: $PYPI_USER
#  password: $PYPI_PASSWORD
#  # Only deploy when a new tag is made in github
#  on:
#    tags: true
#  # Only send to pypi once, intead of trying for every python build
#  skip_existing: true
