language: python

jobs:
  include:
    - stage: "Tests"
      name: "Test bionic Python 3.6"
      os: linux
      dist: bionic
      python: "3.6"
      env: TOXENV=py36
    - name: "Test bionic Python 3.8"
      os: linux
      dist: bionic
      python: "3.8"
      env: TOXENV=py38
    - name: "Test OSX PYthon 3.8"
      os: osx
      python: "3.8"
      env TOXENV=py38

install:
  pip install tox

script: tox -e $TOXENV

deploy:
  provider: pypi
  user: $PYPI_USER
  password: $PYPI_PASSWORD
  # Only deploy when a new tag is made in github
  on:
    tags: true
  # Only send to pypi once, intead of trying for every python build
  skip_existing: true
