language: python # this works for Linux but is an error on macOS or Windows


stages:
  - name: test
  - name: deploy
    if: tag IS present

jobs:
  include:
    - stage: test
      name: "Test bionic Python 3.6"
      os: linux
      dist: bionic
      python: "3.6"
      env: TOXENV=py36
    - name: "Test bionic Python 3.8"
      os: linux
      dist: bionic
      python: "3.8"
      env: TOXENV=py38
    - name: "Test OSX Python default version"
      os: osx
      language: shell # 'language: python' is an error on Travis CI macOS
      env:
        - TOXENV=py3
      before_deploy:
        - pip3 install .
        - pip3 install pyinstaller
        - pyinstaller --additional-hooks-dir=pyinstaller_hooks/ travisty/__main__.py  --name travisty --workpath=build/pyinstaller_work --distpath=build
        - tar cvfz travisty.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz build/travisty/
    - name: "Test Windows Python 3.8.0"
      os: windows
      language: shell # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env:
        - PATH=/c/Python38:/c/Python38/Scripts:$PATH
        - TOXENV=py38
      before_deploy:
        - pip3 install .
        - pip3 install pypiwin32
        - pip3 install https://github.com/pyinstaller/pyinstaller/archive/develop.tar.gz # release doesn't work. See https://github.com/pyinstaller/pyinstaller/issues/4265
        - pyinstaller --additional-hooks-dir=pyinstaller_hooks/ travisty/__main__.py  --name travisty --workpath=build/pyinstaller_work --distpath=build
        - tar cvfz travisty.${TRAVIS_OS_NAME}.${TRAVIS_TAG}.tar.gz build/travisty/

install:
  pip install tox

script: tox -e $TOXENV

deploy:
  - provider: releases
    skip_cleanup: true
    on:
      tags: true
      condition: $TRAVIS_OS_NAME = osx || $TRAVIS_OS_NAME = windows
      repo: martinghunt/travisty
    file: $GITHUB_RELEASE_FILE
    api_key:
      secure: "Gibi/yV7KRRs1Ost1upvloXkUdcs9z7V6GNV/9mnVqxFr0CPSd9Vu2BolnFo1Op4BbrCaSOBBAXQ7TljHvQfGc+fz2ITnOd4ZqkHtZsstJUJqKMDOqZy1HFyY9mtdRUv71zZmf82qNHueGluguAvBrBHnMLjA97U4CQOiYZKMDjcLe9LXNe4q2NtrmmmGevFN92zJKJBXfFY0J6jld0zONHGTKL5X/h3R20PZnFvoi8HnYTMi1hrviFD+zCz2dIqrxPjyrctQ3/YHBIwJKtw1zfNKCcdAFV4N/KSjMnl7eIXnV/8CFfZyPHJXY10nnhKMROJmvC7sAo7a6bkjrOJii38NukImP3x3ji1Z9/v57qNclKYXve6EZ/yL9CeVDNRIRRU7Rqf/IE9VhF9DTcxkzlybnw0NbqJOv4awzr6F+yNmvM9GY51J6tH/tt7Af2KyfpLLkhAc4bs6hJbuXLw1WiKPlnTV0SXqEgJcuhWNy4GYT4OmM+Hgp1Z2hqE+OgUIYGp+sgJmf9Q0F/mQN4VCQqBWjvVaa4HZjCBq+OVaOXBke7Bpievcrdw6pnToFCns59+psRCvaM/lNQLT+Vv2iVdq53tnfn5Sm6Kc2nvg1mUOuV0qTpCNjq7dW02nCkEq24dOVvhQ3t4EA5dKAVatmCsw+Hxoxm1LifUnAhhdt0="

